[package]
name = "regex-thompson-counting"
version = "0.1.0"
edition = "2024"
license = "MIT"

[[bin]]
name = "rethoc"
path = "src/main.rs"

[dev-dependencies]
criterion = { version = "0.8", features = ["html_reports"] }
gungraun = "0.17.2"
itertools = "0.10"
regex = "1"

[dependencies]
ahash = "0.8"
indexmap = "2"
memchr = "2.8.0"
regex-syntax = "0.8.9"
serde = { version = "1", features = ["derive"] }
serde_json = "1"

[profile.release]
debug = true

[profile.bench]
debug = true

[[bench]]
name = "flamegraph"
harness = false

[[bench]]
name = "memrange"
harness = false
