//! Grammar-aware regex pattern and input generator for fuzzing.
//!
//! This module provides a structured approach to generating random regex
//! patterns **and** targeted test inputs derived from the pattern's own
//! structure.  The key insight is that randomly generated byte strings
//! almost never match a non-trivial regex, so the fuzzer would only ever
//! observe `false == false` agreements.  By walking the generated pattern
//! AST we can produce:
//!
//! - **Positive candidates** — strings that *should* match the pattern.
//! - **Near-miss mutations** — strings derived from positives that exercise
//!   boundary conditions (off-by-one repeat count, wrong literal, truncation).
//! - **Fixed edge cases** — empty string, null byte, newline, `\xff`, etc.
//!
//! # Architecture
//!
//! The generator is driven by a [`FuzzRng`] — a simple deterministic byte
//! consumer that can be fed from either `libfuzzer-sys::arbitrary` (for
//! `cargo-fuzz`) or `proptest` (for `cargo test`).
//!
//! ```text
//! FuzzRng ──> PatternNode (AST) ──> pattern string
//!                                └──> targeted inputs
//! ```

use std::fmt::Write;

// ---------------------------------------------------------------------------
// Deterministic byte-consumer RNG
// ---------------------------------------------------------------------------

/// A simple deterministic RNG that consumes bytes from a seed buffer.
///
/// This is intentionally *not* a cryptographic or statistically good RNG.
/// It just needs to map fuzzer-provided bytes into generator decisions in a
/// deterministic, reproducible way.
pub struct FuzzRng<'a> {
    data: &'a [u8],
    pos: usize,
}

impl<'a> FuzzRng<'a> {
    /// Create a new RNG consuming bytes from `data`.
    pub fn new(data: &'a [u8]) -> Self {
        Self { data, pos: 0 }
    }

    /// Consume one byte, returning 0 if exhausted.
    fn next_byte(&mut self) -> u8 {
        if self.pos < self.data.len() {
            let b = self.data[self.pos];
            self.pos += 1;
            b
        } else {
            0
        }
    }

    /// Return a value in `0..n` (uniform-ish for small n).
    fn choose(&mut self, n: usize) -> usize {
        if n <= 1 {
            return 0;
        }
        self.next_byte() as usize % n
    }

    /// Return a value in `lo..=hi`.
    fn range(&mut self, lo: usize, hi: usize) -> usize {
        if lo >= hi {
            return lo;
        }
        lo + self.choose(hi - lo + 1)
    }

    /// Return `true` with roughly `percent`% probability.
    fn chance(&mut self, percent: u8) -> bool {
        (self.next_byte() % 100) < percent
    }

    /// Return a number of remaining unconsumed bytes (for extra inputs).
    pub fn remaining(&self) -> &'a [u8] {
        &self.data[self.pos..]
    }
}

// ---------------------------------------------------------------------------
// Pattern AST
// ---------------------------------------------------------------------------

/// A node in the generated pattern AST.
///
/// This is *not* the same as `regex_syntax::hir::Hir` — it is a simpler
/// representation designed for easy generation and targeted input derivation.
#[derive(Debug, Clone)]
pub enum PatternNode {
    /// A single literal byte (e.g. `a`, `\x00`).
    Literal(u8),
    /// The dot metacharacter (matches any byte in `(?s-u)` mode).
    Dot,
    /// A byte class like `[a-c]`.  Stored as inclusive (lo, hi) ranges.
    Class(Vec<(u8, u8)>),
    /// Concatenation of two or more sub-expressions.
    Concat(Vec<PatternNode>),
    /// Alternation (`a|b|c`).
    Alt(Vec<PatternNode>),
    /// A bounded or unbounded repetition.
    Repeat {
        body: Box<PatternNode>,
        kind: RepeatKind,
    },
    /// Start-of-input anchor `^`.
    AnchorStart,
    /// End-of-input anchor `$`.
    AnchorEnd,
    /// Word boundary assertion `\b`.
    WordBoundary,
    /// Non-word-boundary assertion `\B`.
    NotWordBoundary,
}

/// The kind of repetition applied to a sub-expression.
#[derive(Debug, Clone, Copy)]
pub enum RepeatKind {
    /// `?` — zero or one.
    Question,
    /// `*` — zero or more.
    Star,
    /// `+` — one or more.
    Plus,
    /// `{min,max}` — bounded repetition.
    Bounded { min: usize, max: usize },
}

// ---------------------------------------------------------------------------
// Pattern generation
// ---------------------------------------------------------------------------

/// Configuration limits for pattern generation.
const MAX_DEPTH: usize = 3;
const MAX_CONCAT_LEN: usize = 5;
const MAX_ALT_BRANCHES: usize = 4;
const MAX_REPEAT_BOUND: usize = 50;
/// Byte literals we prefer to use — printable ASCII, easy to reason about.
const LITERAL_POOL: &[u8] = b"abcdefxy01 ";

/// Generate a random pattern AST from the fuzzer seed.
///
/// Returns a tuple of `(pattern_string, ast)` where the AST is used to
/// derive targeted inputs.
pub fn generate_pattern(rng: &mut FuzzRng<'_>) -> (String, PatternNode) {
    let body = gen_expr(rng, 0);

    // Decide anchoring strategy.
    let anchoring = rng.choose(4);
    let ast = match anchoring {
        0 => {
            // ^body$  — fully anchored
            PatternNode::Concat(vec![PatternNode::AnchorStart, body, PatternNode::AnchorEnd])
        }
        1 => {
            // ^body  — start-anchored
            PatternNode::Concat(vec![PatternNode::AnchorStart, body])
        }
        2 => {
            // body$  — end-anchored
            PatternNode::Concat(vec![body, PatternNode::AnchorEnd])
        }
        _ => {
            // body  — unanchored
            body
        }
    };

    let mut pattern = String::new();
    render_node(&ast, &mut pattern);
    (pattern, ast)
}

/// Recursively generate a pattern expression.
fn gen_expr(rng: &mut FuzzRng<'_>, depth: usize) -> PatternNode {
    if depth >= MAX_DEPTH {
        return gen_atom(rng);
    }

    match rng.choose(5) {
        // Concatenation
        0 => {
            let len = rng.range(2, MAX_CONCAT_LEN);
            let children: Vec<_> = (0..len).map(|_| gen_piece(rng, depth)).collect();
            PatternNode::Concat(children)
        }
        // Alternation
        1 => {
            let n = rng.range(2, MAX_ALT_BRANCHES);
            let branches: Vec<_> = (0..n).map(|_| gen_piece(rng, depth + 1)).collect();
            PatternNode::Alt(branches)
        }
        // Single piece (atom + optional repetition)
        _ => gen_piece(rng, depth),
    }
}

/// Generate a "piece": an atom or group, optionally followed by a repetition.
fn gen_piece(rng: &mut FuzzRng<'_>, depth: usize) -> PatternNode {
    let base = if depth < MAX_DEPTH && rng.chance(40) {
        // Grouped sub-expression (enables nesting)
        gen_expr(rng, depth + 1)
    } else {
        gen_atom(rng)
    };

    // Don't apply repetitions to zero-width assertions — patterns like
    // `^{3}` are degenerate (a zero-width assertion repeated N times is
    // semantically identical to the assertion once).
    let is_zero_width = matches!(
        base,
        PatternNode::AnchorStart
            | PatternNode::AnchorEnd
            | PatternNode::WordBoundary
            | PatternNode::NotWordBoundary
    );

    // ~60% chance of adding a repetition operator (but not to assertions)
    if !is_zero_width && rng.chance(60) {
        let kind = gen_repeat_kind(rng);
        PatternNode::Repeat {
            body: Box::new(base),
            kind,
        }
    } else {
        base
    }
}

/// Generate a leaf atom.
///
/// Mostly byte-consuming atoms (literals, dots, classes), but with a small
/// chance (~10%) of producing a zero-width word boundary assertion (`\b`
/// or `\B`).  These are important for exercising the DFA deferred assertion
/// machinery but should stay rare to avoid degenerate patterns.
fn gen_atom(rng: &mut FuzzRng<'_>) -> PatternNode {
    match rng.choose(11) {
        // Literal byte from pool (6/11 ≈ 55%)
        0..=5 => {
            let idx = rng.choose(LITERAL_POOL.len());
            PatternNode::Literal(LITERAL_POOL[idx])
        }
        // Dot (2/11 ≈ 18%)
        6 | 7 => PatternNode::Dot,
        // Byte class [lo-hi] (1/11 ≈ 9%)
        8 => {
            let num_ranges = rng.range(1, 3);
            let mut ranges = Vec::with_capacity(num_ranges);
            for _ in 0..num_ranges {
                let lo = LITERAL_POOL[rng.choose(LITERAL_POOL.len())];
                let hi_offset = rng.range(0, 5) as u8;
                let hi = lo.saturating_add(hi_offset);
                ranges.push((lo, hi));
            }
            PatternNode::Class(ranges)
        }
        // Word boundary \b (1/11 ≈ 9%)
        9 => PatternNode::WordBoundary,
        // Non-word-boundary \B (1/11 ≈ 9%)
        _ => PatternNode::NotWordBoundary,
    }
}

/// Generate a repetition kind.
fn gen_repeat_kind(rng: &mut FuzzRng<'_>) -> RepeatKind {
    match rng.choose(7) {
        0 => RepeatKind::Question,
        1 => RepeatKind::Star,
        2 => RepeatKind::Plus,
        _ => {
            // Bounded {min,max}
            let min = rng.range(0, 10);
            let max = rng.range(min, MAX_REPEAT_BOUND);
            RepeatKind::Bounded { min, max }
        }
    }
}

// ---------------------------------------------------------------------------
// Pattern rendering (AST -> regex string)
// ---------------------------------------------------------------------------

/// Render a [`PatternNode`] into a regex pattern string.
fn render_node(node: &PatternNode, out: &mut String) {
    match node {
        PatternNode::Literal(b) => render_literal(*b, out),
        PatternNode::Dot => out.push('.'),
        PatternNode::Class(ranges) => {
            out.push('[');
            for &(lo, hi) in ranges {
                if lo == hi {
                    render_class_byte(lo, out);
                } else {
                    render_class_byte(lo, out);
                    out.push('-');
                    render_class_byte(hi, out);
                }
            }
            out.push(']');
        }
        PatternNode::Concat(children) => {
            for child in children {
                render_node(child, out);
            }
        }
        PatternNode::Alt(branches) => {
            out.push('(');
            for (i, branch) in branches.iter().enumerate() {
                if i > 0 {
                    out.push('|');
                }
                render_node(branch, out);
            }
            out.push(')');
        }
        PatternNode::Repeat { body, kind } => {
            // Wrap non-trivial bodies in a group for correct precedence.
            let needs_group = matches!(body.as_ref(), PatternNode::Concat(_) | PatternNode::Alt(_));
            if needs_group {
                out.push('(');
                render_node(body, out);
                out.push(')');
            } else {
                render_node(body, out);
            }
            match kind {
                RepeatKind::Question => out.push('?'),
                RepeatKind::Star => out.push('*'),
                RepeatKind::Plus => out.push('+'),
                RepeatKind::Bounded { min, max } => {
                    let _ = write!(out, "{{{},{}}}", min, max);
                }
            }
        }
        PatternNode::AnchorStart => out.push('^'),
        PatternNode::AnchorEnd => out.push('$'),
        PatternNode::WordBoundary => out.push_str("\\b"),
        PatternNode::NotWordBoundary => out.push_str("\\B"),
    }
}

/// Render a literal byte, escaping regex metacharacters.
fn render_literal(b: u8, out: &mut String) {
    match b {
        // Metacharacters that need escaping
        b'.' | b'^' | b'$' | b'*' | b'+' | b'?' | b'(' | b')' | b'[' | b']' | b'{' | b'}'
        | b'|' | b'\\' => {
            out.push('\\');
            out.push(b as char);
        }
        // Printable ASCII
        0x20..=0x7E => out.push(b as char),
        // Non-printable: use hex escape
        _ => {
            let _ = write!(out, "\\x{:02x}", b);
        }
    }
}

/// Render a byte inside a character class `[...]`, escaping only class-special chars.
fn render_class_byte(b: u8, out: &mut String) {
    match b {
        b']' | b'\\' | b'^' | b'-' => {
            out.push('\\');
            out.push(b as char);
        }
        0x20..=0x7E => out.push(b as char),
        _ => {
            let _ = write!(out, "\\x{:02x}", b);
        }
    }
}

// ---------------------------------------------------------------------------
// Pattern-aware input generation
// ---------------------------------------------------------------------------

/// Generate a set of targeted test inputs derived from the pattern AST,
/// plus fixed edge-case inputs.
///
/// Returns a `Vec<Vec<u8>>` of byte strings to test against the pattern.
/// The inputs include:
///
/// 1. **Positive candidates** — strings that likely match the core body
///    of the pattern (ignoring anchors for generation, since they affect
///    *where* we match, not *what* bytes).
/// 2. **Near-miss mutations** — boundary-condition inputs derived from
///    the positives (off-by-one repeat counts, wrong literals, etc.).
/// 3. **Fixed edge cases** — always included regardless of pattern.
pub fn generate_inputs(rng: &mut FuzzRng<'_>, ast: &PatternNode) -> Vec<Vec<u8>> {
    let mut inputs = Vec::new();

    // Generate several positive candidates.
    for _ in 0..8 {
        let mut buf = Vec::new();
        gen_matching_input(rng, ast, &mut buf);
        inputs.push(buf);
    }

    // Generate near-miss mutations from the first few positives.
    let num_positives = inputs.len();
    for i in 0..num_positives.min(4) {
        let base = inputs[i].clone();
        // Truncated prefix
        if base.len() > 1 {
            inputs.push(base[..base.len() / 2].to_vec());
        }
        // Extended with extra bytes
        let mut extended = base.clone();
        extended.extend_from_slice(b"zzz");
        inputs.push(extended);
        // Single-byte flip
        if !base.is_empty() {
            let mut flipped = base.clone();
            let idx = rng.choose(flipped.len());
            flipped[idx] = flipped[idx].wrapping_add(1);
            inputs.push(flipped);
        }
        // Off-by-one: remove last byte
        if !base.is_empty() {
            inputs.push(base[..base.len() - 1].to_vec());
        }
    }

    // Fixed edge-case inputs (always included).
    inputs.push(vec![]); // empty
    inputs.push(vec![0x00]); // null byte
    inputs.push(vec![b'\n']); // newline (anchor edge cases)
    inputs.push(vec![b'\r', b'\n']); // CRLF
    inputs.push(vec![0xFF]); // high byte
    inputs.push(vec![b'a']); // single common literal
    inputs.push(b"aaa".to_vec());
    inputs.push(b"abc".to_vec());

    // Repeated-char inputs (exercise counter boundaries).
    for &ch in b"ax0" {
        for &len in &[0, 1, 2, 5, 10, 20, 50] {
            inputs.push(vec![ch; len]);
        }
    }

    // Add any extra fuzzer-provided bytes as raw inputs.
    let remaining = rng.remaining();
    if remaining.len() >= 2 {
        // Split remaining bytes into multiple inputs at zero-byte boundaries.
        for chunk in remaining.split(|&b| b == 0) {
            if !chunk.is_empty() {
                inputs.push(chunk.to_vec());
            }
        }
    }

    inputs
}

/// Walk the AST and generate a byte string that likely matches the pattern.
///
/// This is best-effort: for complex patterns with look-arounds the generated
/// string may not actually match, but it will contain the right literals and
/// repetition counts, which is what matters for exercising the matcher.
fn gen_matching_input(rng: &mut FuzzRng<'_>, node: &PatternNode, out: &mut Vec<u8>) {
    match node {
        PatternNode::Literal(b) => out.push(*b),
        PatternNode::Dot => {
            // Pick a random printable byte.
            let b = LITERAL_POOL[rng.choose(LITERAL_POOL.len())];
            out.push(b);
        }
        PatternNode::Class(ranges) => {
            // Pick a random range, then a random byte within it.
            if ranges.is_empty() {
                return;
            }
            let &(lo, hi) = &ranges[rng.choose(ranges.len())];
            let b = if lo <= hi {
                lo + (rng.next_byte() % (hi - lo + 1))
            } else {
                lo
            };
            out.push(b);
        }
        PatternNode::Concat(children) => {
            for child in children {
                gen_matching_input(rng, child, out);
            }
        }
        PatternNode::Alt(branches) => {
            // Pick one branch.
            if branches.is_empty() {
                return;
            }
            let idx = rng.choose(branches.len());
            gen_matching_input(rng, &branches[idx], out);
        }
        PatternNode::Repeat { body, kind } => {
            let count = match kind {
                RepeatKind::Question => rng.range(0, 1),
                RepeatKind::Star => rng.range(0, 8),
                RepeatKind::Plus => rng.range(1, 8),
                RepeatKind::Bounded { min, max } => rng.range(*min, *max),
            };
            for _ in 0..count {
                gen_matching_input(rng, body, out);
            }
        }
        // Anchors and word boundaries don't produce bytes.
        PatternNode::AnchorStart
        | PatternNode::AnchorEnd
        | PatternNode::WordBoundary
        | PatternNode::NotWordBoundary => {}
    }
}

// ---------------------------------------------------------------------------
// Tests
// ---------------------------------------------------------------------------

// ---------------------------------------------------------------------------
// Bounded-gap pattern generation
// ---------------------------------------------------------------------------

/// Maximum gap bound for generated bounded-gap patterns.
const BG_MAX_GAP: usize = 100;
/// Maximum anchor length (sum of literal + exact-repetition pieces).
const BG_MAX_ANCHOR_PIECES: usize = 4;

/// Generate a pattern guaranteed to be recognised by the bounded-gap
/// specialisation probe: `Anchor (Gap Anchor)* Gap?` with fixed-length,
/// assertion-free anchors and single-byte bounded gaps.
///
/// Returns `(pattern_string, ast)` where the AST can be used for
/// targeted input generation via [`generate_inputs`].
pub fn generate_bounded_gap_pattern(rng: &mut FuzzRng<'_>) -> (String, PatternNode) {
    // Decide chain shape.
    let num_anchors = rng.range(1, 4); // 1–4 anchors
    let has_tail_gap = num_anchors == 1 || rng.chance(40);

    // Decide whole-pattern anchoring.
    let start_anchored = rng.chance(25);
    let end_anchored = rng.chance(25);

    let mut pieces: Vec<PatternNode> = Vec::new();

    if start_anchored {
        pieces.push(PatternNode::AnchorStart);
    }

    for i in 0..num_anchors {
        // Generate a fixed-length, assertion-free anchor.
        pieces.push(gen_bg_anchor(rng));

        // Interior gap between anchors.
        if i < num_anchors - 1 {
            pieces.push(gen_bg_gap(rng));
        }
    }

    // Optional trailing gap.
    if has_tail_gap {
        pieces.push(gen_bg_gap(rng));
    }

    if end_anchored {
        pieces.push(PatternNode::AnchorEnd);
    }

    let ast = if pieces.len() == 1 {
        pieces.pop().unwrap()
    } else {
        PatternNode::Concat(pieces)
    };

    let mut pattern = String::new();
    render_node(&ast, &mut pattern);
    (pattern, ast)
}

/// Generate a fixed-length, assertion-free anchor fragment.
///
/// Produces a concatenation of 1–4 pieces, each being a literal byte
/// or a fixed-count repetition of a single byte/class (e.g. `a{3}`).
/// All branches of alternations have equal length.
fn gen_bg_anchor(rng: &mut FuzzRng<'_>) -> PatternNode {
    let num_pieces = rng.range(1, BG_MAX_ANCHOR_PIECES);
    if num_pieces == 1 {
        gen_bg_anchor_piece(rng)
    } else {
        let children: Vec<_> = (0..num_pieces).map(|_| gen_bg_anchor_piece(rng)).collect();
        PatternNode::Concat(children)
    }
}

/// Generate one fixed-length anchor piece: a literal, a byte class,
/// or a fixed-count repetition.
fn gen_bg_anchor_piece(rng: &mut FuzzRng<'_>) -> PatternNode {
    match rng.choose(6) {
        // Literal byte (3/6 = 50%).
        0..=2 => {
            let idx = rng.choose(LITERAL_POOL.len());
            PatternNode::Literal(LITERAL_POOL[idx])
        }
        // Byte class (1/6 ≈ 17%).
        3 => {
            let num_ranges = rng.range(1, 3);
            let mut ranges = Vec::with_capacity(num_ranges);
            for _ in 0..num_ranges {
                let lo = LITERAL_POOL[rng.choose(LITERAL_POOL.len())];
                let hi_offset = rng.range(0, 5) as u8;
                let hi = lo.saturating_add(hi_offset);
                ranges.push((lo, hi));
            }
            PatternNode::Class(ranges)
        }
        // Fixed-count repetition of a byte/class (2/6 ≈ 33%).
        _ => {
            let count = rng.range(1, 6);
            let body = match rng.choose(3) {
                0 => PatternNode::Dot,
                1 => {
                    let idx = rng.choose(LITERAL_POOL.len());
                    PatternNode::Literal(LITERAL_POOL[idx])
                }
                _ => {
                    let lo = LITERAL_POOL[rng.choose(LITERAL_POOL.len())];
                    let hi = lo.saturating_add(rng.range(0, 5) as u8);
                    PatternNode::Class(vec![(lo, hi)])
                }
            };
            PatternNode::Repeat {
                body: Box::new(body),
                kind: RepeatKind::Bounded {
                    min: count,
                    max: count,
                },
            }
        }
    }
}

/// Generate a bounded gap: a single-byte predicate with finite bounds.
fn gen_bg_gap(rng: &mut FuzzRng<'_>) -> PatternNode {
    let min = rng.range(0, 20);
    let max = rng.range(min, BG_MAX_GAP);

    // Gap body: dot (wildcard) or a byte class.
    let body = match rng.choose(4) {
        // Dot (75%) — most common in practice.
        0..=2 => PatternNode::Dot,
        // Byte class (25%) — e.g. [^/].
        _ => {
            let lo = LITERAL_POOL[rng.choose(LITERAL_POOL.len())];
            let hi = lo.saturating_add(rng.range(0, 10) as u8);
            PatternNode::Class(vec![(lo, hi)])
        }
    };

    PatternNode::Repeat {
        body: Box::new(body),
        kind: RepeatKind::Bounded { min, max },
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_generate_pattern_deterministic() {
        let seed = b"hello world this is a seed for the fuzzer";
        let (p1, _) = generate_pattern(&mut FuzzRng::new(seed));
        let (p2, _) = generate_pattern(&mut FuzzRng::new(seed));
        assert_eq!(p1, p2, "same seed must produce same pattern");
    }

    #[test]
    fn test_generate_pattern_parseable() {
        // Try many seeds and verify every generated pattern parses.
        for i in 0u16..500 {
            let seed = i.to_le_bytes();
            let (pattern, _) = generate_pattern(&mut FuzzRng::new(&seed));
            let full = format!("(?s-u){}", pattern);
            let result = regex_syntax::parse(&full);
            assert!(
                result.is_ok(),
                "generated pattern should parse: `{}`, error: {:?}",
                pattern,
                result.err()
            );
        }
    }

    #[test]
    fn test_generate_inputs_nonempty() {
        let seed = b"test seed";
        let (_, ast) = generate_pattern(&mut FuzzRng::new(seed));
        let inputs = generate_inputs(&mut FuzzRng::new(b"input seed"), &ast);
        // We should always get at least the edge-case inputs.
        assert!(
            inputs.len() >= 10,
            "expected at least 10 inputs, got {}",
            inputs.len()
        );
    }

    #[test]
    fn test_render_escaping() {
        let node = PatternNode::Literal(b'.');
        let mut out = String::new();
        render_node(&node, &mut out);
        assert_eq!(out, "\\.");
    }

    #[test]
    fn test_bounded_repeat_render() {
        let node = PatternNode::Repeat {
            body: Box::new(PatternNode::Literal(b'a')),
            kind: RepeatKind::Bounded { min: 2, max: 5 },
        };
        let mut out = String::new();
        render_node(&node, &mut out);
        assert_eq!(out, "a{2,5}");
    }

    #[test]
    fn test_star_plus_question_render() {
        let cases = [
            (RepeatKind::Question, "a?"),
            (RepeatKind::Star, "a*"),
            (RepeatKind::Plus, "a+"),
        ];
        for (kind, expected) in &cases {
            let node = PatternNode::Repeat {
                body: Box::new(PatternNode::Literal(b'a')),
                kind: *kind,
            };
            let mut out = String::new();
            render_node(&node, &mut out);
            assert_eq!(&out, expected);
        }
    }

    #[test]
    fn test_nested_repeat_render() {
        // (a+){2,3}
        let inner = PatternNode::Repeat {
            body: Box::new(PatternNode::Literal(b'a')),
            kind: RepeatKind::Plus,
        };
        let outer = PatternNode::Repeat {
            body: Box::new(inner),
            kind: RepeatKind::Bounded { min: 2, max: 3 },
        };
        let mut out = String::new();
        render_node(&outer, &mut out);
        assert_eq!(out, "a+{2,3}");
    }

    #[test]
    fn test_class_render() {
        let node = PatternNode::Class(vec![(b'a', b'c'), (b'x', b'z')]);
        let mut out = String::new();
        render_node(&node, &mut out);
        assert_eq!(out, "[a-cx-z]");
    }
}
